version: '3.9'

services:

  app:
    image: anikondu87/transcription-app:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - traefik-net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transcription.rule=Host(`transcription.hamsterdeal.ch`)"
        - "traefik.http.routers.transcription.entrypoints=websecure"
        - "traefik.http.services.transcription.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-net"
networks:
  traefik-net:
    external: true
