version: '3.9'

services:

  app:
    image: anikondu87/transcription-app:latest
    secrets:
      - openai_api_key
    environment:
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
    networks:
      - traefik-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.transcription.rule=Host(`transcription.hamsterdeal.ch`)"
        - "traefik.http.routers.transcription.entrypoints=websecure"
        - "traefik.http.services.transcription.loadbalancer.server.port=8080"
networks:
  traefik-net:
    external: true

secrets:
  openai_api_key:
    external: true